services:
  - type: web
    name: aslan-food-kebab-builder
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: API_PREFIX
        value: /api
      - key: API_VERSION
        value: v1
      # MongoDB is optional - kebab builder works with static data
      # - key: MONGODB_URI
      #   value: your-mongodb-connection-string
    healthCheckPath: /api/health
    disk:
      name: aslan-food-disk
      mountPath: /opt/render/project/logs
      sizeGB: 1